### ISSUE TITLE
对于剪切区域，如何调整大小

### ISSUE THREAD

**Issue by cfanbo** [ElemeFE/image-cropper#2]
默认情况下是正方型，100x100的(比例绽放),但需求是高度与宽度不一样，这个如何调整？

**Comment by furybean** [comment]
目前没有开放选项，例子也得有点调整，争取这个周末做掉吧。

**Comment by cfanbo** [comment]
好的，那周一过来看, 辛苦了！

**Comment by furybean** [comment]
更新到了0.3.0版本：
增加了aspectRatio的选项，设置为非数字，则为任意宽高比。

文档也已经补充到首页上了，例子可参考demo/standalone-noar.html。

**Comment by cfanbo** [comment]
难道不能限制高与宽的比较值么？如 2:1 再在是要么1:1，要么是任意，想在客户端对比例限制一下

**Comment by furybean** [comment]
可以，设置为2，则宽高比为2。设置为字符串则为任意比例。
