### ISSUE TITLE
request a plain js version

### ISSUE THREAD

**Issue by kockok** [ElemeFE/image-cropper#4]
Can you do a plain js version instead of making it modular? Thanks.

**Comment by furybean** [comment]
dist/cropper.js is the plain js version, demo/*.html is using dist/cropper.js.

**Comment by kockok** [comment]
Sorry, I mean a version with no "require" at all, plus stripping all angular stuff, is that possible?

**Comment by furybean** [comment]
Update version to 0.3.1, you can build plain js version now.
1. clone/download this repo
2. run npm install in command line.
3. use npm run build-plain in command line.
4. use dist/cropper-plain.js
