### ISSUE TITLE
怎么获取裁剪后的图片？

### ISSUE THREAD

**Issue by Abel-Liu** [ElemeFE/image-cropper#6]
有没有函数，是需要手动裁剪吗？
谢谢。

**Comment by furybean** [comment]
我可以增加一个工具方法，但是这个方法只能在 IE9 以上浏览器执行。

**Comment by Abel-Liu** [comment]
我知道怎么做了，这个你不用必须加。多谢回复。

**Comment by zhouzhongyuan** [comment]
怎么才能获取呢？

**Comment by furybean** [comment]
使用 canvas 的 drawImage，然后把 canvas 转成 base64： http://stackoverflow.com/questions/15685698/getting-binary-base64-data-from-html5-canvas-readasbinarystring

**Comment by Abel-Liu** [comment]
我是上传到服务器再裁剪的，拿到img的src（base64），还有X、Y、Width、Height
