### ISSUE TITLE
无法获取裁剪的值

### ISSUE THREAD

**Issue by Abel-Liu** [ElemeFE/image-cropper#7]
隐藏域的值没有

![11](https://cloud.githubusercontent.com/assets/7625589/11808218/082e1b56-a35a-11e5-85ca-4c8ca0348754.jpg)

**Comment by furybean** [comment]
其实有两个问题，http://elemefe.github.io/image-cropper/ 上的例子，那个例子使用 new Cropper 实现的，本身就不能更改 input 的值，需要在 onCroppedRectChange 事件里面获取。

另一个问题，是 angular-demo.html 确实有问题，忘记加 ng-controller="demoControll"。

这两个问题刚刚都已经修复。
